services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    hostname: mongo1
    ports:
      - "27017:27017"
    command: mongod --replSet myReplicaSet --bind_ip_all --port 27017
    networks:
      - mongo-net
    volumes:
      - mongo1-data:/data/db
    restart: unless-stopped

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    hostname: mongo2
    ports:
      - "27018:27018"
    command: mongod --replSet myReplicaSet --bind_ip_all --port 27018
    networks:
      - mongo-net
    volumes:
      - mongo2-data:/data/db
    restart: unless-stopped

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    hostname: mongo3
    ports:
      - "27019:27019"
    command: mongod --replSet myReplicaSet --bind_ip_all --port 27019
    networks:
      - mongo-net
    volumes:
      - mongo3-data:/data/db
    restart: unless-stopped

networks:
  mongo-net:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: